### ISSUE TITLE
Export file error on family table instances

### ISSUE THREAD

**Issue by RMT-ME-AB** [Zepmanbc/creopyson#90]
* Creo version: 7.0.6.0
* Creopyson version: 0.7.7
* Creoson version: 2.9.0
* Python version: 3.12.4
* Operating System: Windows 

### Description

When exporting some family table instances as step files using interface_export_file creopyson throws "File name contains an invalid character: <".  I believe this is happening because creo formats family table instance file names as "instance_name<generic_name>.prt"

### What I Did

```
To get around this I had to use the filename flag in the export_file so that it used the "instance_name.prt" format that I fed the function instead of the instance_name<generic_name>.prt format the creo returned
```

**Comment by adama2000** [comment]
Another workaround might be to do a file-open first on the part, because
the file open function takes a "generic" parameter.  You would set the
"file" parameter to instance_name.prt and the "generic" parameter to
generic_name.  After you do the file-open then you could do the export_file
without specifying a file because it would use the currently active model.

I haven't tested it myself, but it might work.

Adam Andrews
